---
- name: 🔥 Install firewall package
  package:
    name:
      - ufw
    state: present
  tags:
    - config.firewall

# - name: 🔥 Deny all ingress connections
#   ufw:
#     policy: deny
#     direction: incoming
#   tags:
#     - config.firewall

- name: 🔥 allow ingress ssh
  ufw:
    rule: allow
    port: ssh
    proto: tcp
    direction: in
  tags:
    - config.firewall

- name: 🔥 allow ingress solana udp ports
  ufw:
    rule: allow
    proto: udp
    direction: in
    port: "{{ open_solana_ports_start }}:{{ open_solana_ports_end }}"
  tags:
    - config.firewall

- name: 🔥 allow ingress solana tcp ports
  ufw:
    rule: allow
    proto: tcp
    direction: in
    port: "{{ open_solana_ports_start }}:{{ open_solana_ports_end }}"
  tags:
    - config.firewall

- name: 🔥 Enable ufw
  ufw:
    state: enabled
  tags:
    - config.firewall
