---

- name: 📦 Install additional packages
  import_tasks: packages.yaml
  tags:
    - config.packages

#- name: 🤹 Create swap
#  import_tasks: swap.yaml
# tags:
#    - config.swap
#  when: swap_file_size_gb | int  > 0
#
#- name: 💾 Create ramdisk
#  import_tasks: ramdisk.yaml
#  tags:
#    - config.ramdisk
#  when: use_ramdisk_for_account

#- name: 🏎 Config cpu governor performance mode
# import_tasks: governor.yaml
#  tags:
#   - config.cpu

- name: 🔥 Config firewall
  import_tasks: firewall.yaml
  tags:
    - config.firewall
  when:
    use_firewall | bool

- name: 🚫 Config file2ban
  import_tasks: fail2ban.yaml
  tags:
    - config.fail2ban

- name: 🐸 Create solana user
  import_tasks: solana_user.yaml
  tags:
    - config.solana_user
    - validator.service.solana

- name: 🔧 Config sysctl
  import_tasks: sysctl.yaml

- name: ⌚ chronly
  import_tasks: chronly.yaml

